"""The data tree is sound, derived, and found the way the rest of OVOS finds
a language.

The first gate runs the same check a checkout runs before a release, on the
shipped tree. The rest pins what a consumer may rely on: what the sources
say about the languages the fleet speaks (a handful of sentinel facts, not
the lists themselves, which the generator owns), regions reading their
language's file with their own differences on top, an undescribed language
getting nothing, and a tree named by the environment read instead of the
installed one.
"""
from __future__ import annotations

import pathlib

import pytest

import thalovant_languages as languages


@pytest.fixture(autouse=True)
def _installed_data(monkeypatch):
    monkeypatch.delenv(languages.ENV_OVERRIDE, raising=False)
    languages.refresh()
    yield
    languages.refresh()


def test_the_shipped_tree_passes_the_check():
    assert languages.check() == []


def test_the_check_names_what_is_wrong(tmp_path):
    bad = tmp_path / "xx"
    bad.mkdir()
    (bad / "language.yaml").write_text(
        "continuation_words: [the, on]\n"
        "question_patterns: ['(']\n"
        "plural: {some: 'n = 1', one: 'n ~ 1'}\n"
        "colour_words: [red]\n"
        "lowercase_map: {a: A}\n",
        encoding="utf-8",
    )
    problems = languages.check(tmp_path)
    text = "\n".join(problems)
    assert "colour_words" in text and "not a key" in text
    assert "quote a word" in text, problems
    assert "does not compile" in text
    assert "'some' is not a category" in text and "cannot read" in text
    assert "not upper to lower" in text
    assert "scripts.yaml: missing" in text


def test_every_file_is_generated_and_says_from_what():
    """A file written by hand would drift from the sources; the header of
    every one names the generator and the versions it read."""
    for tag in languages.described():
        head = (languages.DATA_ROOT / tag / "language.yaml").read_text(encoding="utf-8").splitlines()[:2]
        assert "Generated by scripts/derive.py" in head[0], tag
        assert head[1].startswith("# Sources: ") and any(
            source in head[1] for source in ("Universal Dependencies", "CLDR", "Unicode")), tag
    head = (languages.DATA_ROOT / "scripts.yaml").read_text(encoding="utf-8").splitlines()[0]
    assert "Generated by scripts/derive.py" in head


def test_the_fleet_speaks_many_languages_now():
    described = languages.described()
    assert len(described) > 200
    with_words = [t for t in described if languages.language(t).get("continuation_words")]
    assert len(with_words) > 120, len(with_words)
    with_plural = [t for t in described if languages.language(t).get("plural")]
    assert len(with_plural) > 150, len(with_plural)


def test_what_the_sources_say_about_english():
    """Sentinels, not the lists: the treebanks own those."""
    en = languages.language("en-US")
    continuation = languages.words("en", "continuation_words")
    assert {"the", "a", "to", "of", "and", "my", "is"} <= continuation
    # "on" ends "turn it on" six times in a hundred, and the data knows it.
    assert "on" not in continuation
    # No half of a contraction is a word anybody says on its own.
    assert not any(word.startswith(("'", "’")) or word in ("ca", "don", "wo") for word in continuation)
    assert {"what", "where", "how", "is", "do", "can", "when"} <= set(en["question_openers"])
    assert en["written_forms"] == {"i": "I"}
    assert en["plural"] == {"one": "i = 1 and v = 0"}
    assert en["slot_examples"]["level"] == "fifty"


def test_what_the_sources_say_about_french():
    fr = languages.language("fr-CA")
    assert {"le", "la", "de", "à", "et", "mon"} <= languages.words("fr", "continuation_words")
    assert {"quel", "quelle", "où", "comment", "combien", "pourquoi"} <= set(fr["question_openers"])
    assert {"quel", "quelle"} <= set(fr["question_words_anywhere"])
    assert fr["plural"] == {"one": "i = 0,1", "many": "e = 0 and i != 0 and i % 1000000 = 0 and v = 0 or e != 0..5"}
    assert fr["question_patterns"] and fr["speech_substitutions"]


def test_what_unicode_says_about_turkish_and_azeri():
    for tag in ("tr", "az"):
        assert list(languages.language(tag)["lowercase_map"].items()) == [("İ", "i"), ("I", "ı")]
    assert "lowercase_map" not in languages.language("de")


def test_a_language_written_without_spaces_still_has_its_particles():
    assert "の" in languages.words("ja", "continuation_words")
    assert languages.script_pattern("unspaced").search("今日")


def test_a_region_reads_its_language_file_with_its_own_differences_on_top(tmp_path, monkeypatch):
    assert languages.language("fr-CA")["continuation_words"] == languages.language("fr")["continuation_words"]
    assert languages.language("en-GB")["question_openers"] == languages.language("en")["question_openers"]
    # A regional file carries only what differs; the language's file is
    # underneath it. (CLDR happens to give pt-PT the same rule as pt today.)
    tree = tmp_path / "languages"
    (tree / "xq").mkdir(parents=True)
    (tree / "xq-ZZ").mkdir()
    (tree / "xq" / "language.yaml").write_text("continuation_words: [zu]\nplural: {one: 'n = 1'}\n", encoding="utf-8")
    (tree / "xq-ZZ" / "language.yaml").write_text("plural: {one: 'i = 0..1'}\n", encoding="utf-8")
    (tree / "scripts.yaml").write_text((languages.DATA_ROOT / "scripts.yaml").read_text(encoding="utf-8"), encoding="utf-8")
    monkeypatch.setenv(languages.ENV_OVERRIDE, str(tree))
    languages.refresh()
    assert languages.language("xq-ZZ") == {"continuation_words": ["zu"], "plural": {"one": "i = 0..1"}}
    assert languages.plural_category("xq-ZZ", 0) == "one" and languages.plural_category("xq", 0) == "other"


def test_a_language_nothing_describes_gets_no_rule_rather_than_another_language_s():
    assert languages.language("tlh") == {}
    assert languages.language(None) == {}
    assert languages.language("") == {}


def test_word_lists_are_lower_cased_and_unite_when_no_language_is_named():
    assert "the" in languages.words("en", "trailing_words")
    assert "la" in languages.words("fr-CA", "trailing_words")
    everything = languages.words(None, "trailing_words")
    assert {"the", "la", "der"} <= everything
    assert languages.words("tlh", "trailing_words") == frozenset()


def test_script_classes_match_their_own_characters_and_nothing_else():
    unspaced = languages.script_pattern("unspaced")
    assert unspaced.search("今天") and unspaced.search("สวัสดี") and unspaced.search("ສະບາຍດີ")
    assert not unspaced.search("hello") and not unspaced.search("안녕")
    syllabic = languages.script_pattern("syllabic")
    assert syllabic.search("안녕") and syllabic.search("今天")
    assert not syllabic.search("สวัสดี") and not syllabic.search("bonjour")
    assert not languages.script_pattern("no-such-kind").search("anything at all")
    assert int(languages.scripts()["unspaced"]["characters_per_word"]) == 2


def test_the_marks_that_close_a_sentence_come_from_unicode_plus_two_measured_ones():
    spaced = languages.marks("sentence_ends", "spaced")
    unspaced = languages.marks("sentence_ends", "unspaced")
    assert {".", "!", "?", "؟", "।"} <= set(spaced)
    assert {"…", ";"} <= set(spaced), "the two the synthesiser splits on"
    assert {"。", "！", "？"} <= set(unspaced)
    assert "," in languages.marks("clause_breaks", "spaced") and "、" in languages.marks("clause_breaks", "unspaced")
    assert ";" not in languages.marks("clause_breaks", "spaced")
    assert languages.marks("no-such-kind", "spaced") == ""


def test_a_checkout_named_by_the_environment_is_read_instead(tmp_path, monkeypatch):
    """Trying a language before it is released: a directory, no code."""
    tree = tmp_path / "languages"
    (tree / "xq").mkdir(parents=True)
    (tree / "xq" / "language.yaml").write_text("continuation_words: [zu]\nplural: {one: 'n = 1'}\n",
                                               encoding="utf-8")
    (tree / "scripts.yaml").write_text(
        (languages.DATA_ROOT / "scripts.yaml").read_text(encoding="utf-8"), encoding="utf-8")
    monkeypatch.setenv(languages.ENV_OVERRIDE, str(tree))
    languages.refresh()
    assert languages.root() == tree
    assert languages.described() == ("xq",)
    assert languages.language("xq-ZZ") == {"continuation_words": ["zu"], "plural": {"one": "n = 1"}}
    assert languages.plural_category("xq", 1) == "one" and languages.plural_category("xq", 3) == "other"
    assert languages.language("en") == {}
    assert languages.check() == []


def test_the_installed_tree_is_where_the_package_is():
    assert languages.DATA_ROOT == pathlib.Path(languages.__file__).resolve().parent / "languages"
    assert (languages.DATA_ROOT / "scripts.yaml").is_file()
