#!/usr/bin/env python3
"""Generate Chinese script word lists from the committed mixed-script treebanks.

Run after changing zh/language.yaml, or use --check to detect stale output.
OpenCC is an authoring dependency; consumers read ordinary packaged YAML.
"""
from __future__ import annotations

import argparse
from importlib.metadata import version
from pathlib import Path

import yaml
from opencc import OpenCC

OUT = Path(__file__).resolve().parents[1] / "src/thalovant_languages/languages"
WORD_KEYS = ("continuation_words", "trailing_words", "question_openers", "question_words_anywhere")


def derive_chinese(out: Path, *, check: bool = False) -> None:
    """Write only word-list differences; the loader inherits other Chinese rules."""
    source = out / "zh/language.yaml"
    data = yaml.safe_load(source.read_text(encoding="utf-8"))
    for tag, config in (("zh-Hans", "t2s"), ("zh-Hant", "s2t")):
        converter = OpenCC(config)
        overlay = {
            key: list(dict.fromkeys(converter.convert(word) for word in data[key]))
            for key in WORD_KEYS if key in data
        }
        text = (
            "# Generated by scripts/derive.py and scripts/derive_chinese.py -- do not edit.\n"
            f"# Sources: zh/language.yaml (Universal Dependencies); OpenCC {version('opencc')} {config}.\n"
            "# Change the Chinese source through overrides/zh.yaml, then regenerate.\n"
            "# Script conversion preserves the source word choices; it does not translate dialects.\n"
        ) + yaml.safe_dump(overlay, allow_unicode=True, sort_keys=False, width=100)
        target = out / tag / "language.yaml"
        if check:
            if not target.is_file() or target.read_text(encoding="utf-8") != text:
                raise ValueError(f"{target}: stale; run python scripts/derive_chinese.py")
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(text, encoding="utf-8")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=OUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    derive_chinese(args.out, check=args.check)
